apiVersion: v1
kind: Service
metadata:
  name: {{ include "notification-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4108
      protocol: TCP
      name: http
  selector:
    app: notification-service
