apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: thepetlinks
spec:
  description: ThePetLinks Project
  sourceRepos:
    - https://github.com/ThePetLinks/*
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
