image:
  registry: docker.io
  repository: bitnami/kafka
  tag: 3.6.1
  pullPolicy: IfNotPresent

kraft:
  enabled: true

zookeeper:
  enabled: false

replicaCount: 1

auth:
  enabled: false

listeners:
  client:
    protocol: PLAINTEXT

persistence:
  enabled: false

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 512Mi

metrics:
  kafka:
    enabled: false
