image:
  repository: mail-service
  tag: "latest"
  pullPolicy: Always

service:
  port: 4110

env:
  APP_PORT: "4110"
  DB_HOST: "postgresql.postgres.svc.cluster.local"
  DB_PORT: "5432"
  DB_USER: "thepetlinks"
  DB_PASSWORD: "PeTL!nk@2025$P@ss"
  DB_NAME: "plan_db"
  DB_SSLMODE: "disable"

  S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
  S3_ACCESS_KEY: TCZWD75YUU2R2M1TO2PI
  S3_SECRET_KEY: IHGOPnKFG9IxHapjSKVrhWg4mwcjkdkUyHMo8vUp
  S3_BUCKET: petlinks
  S3_REGION: us-east-1
