apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "video-service.fullname" . }}
  labels:
    app: video-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-service
  template:
    metadata:
      labels:
        app: video-service
    spec:
      containers:
        - name: video-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: APP_PORT
              value: "{{ .Values.env.APP_PORT }}"
            - name: DB_HOST
              value: "{{ .Values.env.DB_HOST }}"
            - name: DB_PORT
              value: "{{ .Values.env.DB_PORT }}"
            - name: DB_USER
              value: "{{ .Values.env.DB_USER }}"
            - name: DB_PASSWORD
              value: "{{ .Values.env.DB_PASSWORD }}"
            - name: DB_NAME
              value: "{{ .Values.env.DB_NAME }}"
            - name: DB_SSLMODE
              value: "{{ .Values.env.DB_SSLMODE }}"
