apiVersion: v1
kind: Service
metadata:
  name: {{ include "video-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4015
      protocol: TCP
      name: http
  selector:
    app: video-service
