apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: ClusterIP
  selector:
    app: gateway
  ports:
    - name: http
      port: 4013
      targetPort: 4013

# helm upgrade --install gateway ./helm/gateway -n petlinks-dev & kubectl delete pod -l app=gateway -n petlinks-dev & kubectl logs -f deployment/gateway -n petlinks-dev

# helm upgrade --install role-service ../services/core/thepetlink-role-service/helm/role-service -n petlinks-dev & kubectl delete pod -l app=role-service -n petlinks-dev & kubectl wait --for=condition=Ready pod -l app=role-service -n petlinks-dev --timeout=60s & kubectl logs -f deployment/role-service -n petlinks-dev
