apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: role-service
spec:
  project: default
  source:
    repoURL: 'https://github.com/ThePetLinks/thepetlinks-infra'
    path: helm-charts/role-service
    targetRevision: main
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: petlinks-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
