apiVersion: v1
kind: Service
metadata:
  name: {{ include "plan-service.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4103
      protocol: TCP
      name: http
  selector:
    app: plan-service


