image:
  repository: "auth-service"
  tag: latest
  pullPolicy: Always

env:
  APP_PORT: "4102"
  DB_USER: "${db_user}"
  DB_PASSWORD: "${db_pass}"
  DB_HOST: "postgresql.postgresql.svc.cluster.local"
  # DB_HOST: "127.0.0.1"
  DB_PORT: "5432"
  DB_NAME: "auth_db"
  DB_SSLMODE: "disable"
  AUTO_MIGRATE: "true"
  JWT_SECRET: "e6166442ffe29104a9f888776f2a39fa0199132e30167062df8cc3778b480b43953167aaf0dfb873ab69e66bf039927b1f76b20baa84815a93ede883dfaedb22"
