name: Build Role Service

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build & Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/thepetlinks/role-service:latest
